### ISSUE TITLE
Error with subscriptions on refreshing graphiql page

### ISSUE THREAD

**Issue by daveoconnor** [tartiflette/tartiflette-aiohttp#76]
Using a fairly by-the-documentation installation I'm getting an error when I refresh the GraphiQL UI when a subscription is running.

Error:

> Error handling request
> Traceback (most recent call last):
>   File "/home/USER/PROJECT/PROJECT/venv/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 418, in start
>     resp = await task
>   File "/home/USER/PROJECT/PROJECT/venv/lib/python3.8/site-packages/aiohttp/web_app.py", line 458, in _handle
>     resp = await handler(request)
>   File "/home/USER/PROJECT/PROJECT/venv/lib/python3.8/site-packages/aiohttp/web_urldispatcher.py", line 158, in handler_wrapper
>     return await result
>   File "/home/USER/PROJECT/PROJECT/venv/lib/python3.8/site-packages/tartiflette_aiohttp/_subscription_ws_handler.py", line 263, in __call__
>     await shield(self._handle_request())
>   File "/home/USER/PROJECT/PROJECT/venv/lib/python3.8/site-packages/tartiflette_aiohttp/_subscription_ws_handler.py", line 257, in _handle_request
>     await self._on_close(connection_context, tasks)
>   File "/home/USER/PROJECT/PROJECT/venv/lib/python3.8/site-packages/tartiflette_aiohttp/_subscription_ws_handler.py", line 233, in _on_close
>     await self._unsubscribe(connection_context, operation_id)
>   File "/home/USER/PROJECT/PROJECT/venv/lib/python3.8/site-packages/tartiflette_aiohttp/_subscription_ws_handler.py", line 141, in _unsubscribe
>     await operation.aclose()
> RuntimeError: aclose(): asynchronous generator is already running
> 

PROJECT/subscription_resolvers.py

```py
import asyncio
from tartiflette import Subscription

@Subscription("Subscription.foos")
async def subscription_foos(parent, args, ctx, info):
    data = [
        {
            "id": 1,
            "name": "one"
        },
        {
            "id": 2,
            "name": "two"
        }
    ]
    while True:
        yield {
            'foos': data
        }
        await asyncio.sleep(1)
```

PROJECT/sdl/Subscription.graphql
```
type Foo {
    id: Int
    name: String
}
type Subscription {
    foos: [Foo]
}
```
Data is as expected.

Let me know if there's any more info I can provide to help with this.

**Comment by abusi** [comment]
Thanks @daveoconnor, will look into it this week.

**Comment by daveoconnor** [comment]
Thank you! 

Probably not urgent. Doesn't seem to break anything, just errors out.

**Comment by daveoconnor** [comment]
I've done some digging into this but it's not an area I'm familiar with so I'd like some feedback before submitting a pull request.

Reading the [async generator](https://www.python.org/dev/peps/pep-0525/#asynchronous-generator-object) pep it states:

> 5. agen.aclose(): Returns an awaitable, that throws a GeneratorExit exception into the generator. The awaitable can either return a yielded value, if agen handled the exception, or agen will be closed and the exception will propagate back to the caller.

In this case it looks it's propagating the exception back to the caller. Wrapping `await operation.aclose()` in a  `try: ... except RuntimeError: ...` makes it work as expected, with the resolver ending as expected.

The issue I'm having is I'm not really sure what's supposed to happen with the exception handler in this case. Can anyone provide some information on that?

**Comment by daveoconnor** [comment]
The more I thought about this the more I thought it smelled a bit funny, even though that works, so looked into what might have changed to cause this.

Seems like it's related to async generator changes in 3.8: https://bugs.python.org/issue38559

I'll try to come up with a pull request for you to review.

**Comment by daveoconnor** [comment]
#81

**Comment by abusi** [comment]
Perfect @daveoconnor thank you.

**Comment by willrogers** [comment]
I see this problem (I can't unsubscribe) and #81 does fix the problem for me.
